default: &default
  adapter: mysql2
  min_messages: WARNING
  reconnect: true
  pool: 1
  port: 3306
  checkout_timeout: 2

development: &default
  adapter: mysql2
  database: cashflow
  min_messages: WARNING
  reconnect: true
  pool: 30
  username: root
  password: 123456
  host: 'localhost'
  port: 3306
  encoding: utf8